### ISSUE TITLE
Refactor Code - Better Variable names

### ISSUE THREAD

**Issue by jarifibrahim** [kakkilaya/JSON-indentor#6]
`c`, `st`, etc variables should be renamed appropriately. The code requires some major refactoring.

**Comment by Rajat-Goyal** [comment]
I agree . I think this was more of a leisure time project. I would like to refactor and make it more usable if the maintainer is okay with it

**Comment by jarifibrahim** [comment]
Adding relevant comments would also be helpful for newcomers.

**Comment by kakkilaya** [comment]
i think i'll close this and open two new issue. One for refactoring code and one for adding comments
